### ISSUE TITLE
Bring back base modpack folder opt in/out

### ISSUE THREAD

**Issue by 0neW0rld** [RobotsOnDrugs/BDSM#12]
Bring back base modpack folder opt in/out. As of v.0.3 there's no way to opt out of downloading mods from either of the map folders.

P.S. the config wizard's prompts don't line up with the actual values being initialized in the config file

**Comment by RobotsOnDrugs** [comment]
In the case of maps, it's entirely reasonable to make this an option, and I will add that back in with an additional prompt in the wizard. I won't add the rest to the prompts in the wizard since there is rarely ever a reason to have them off, but I will make it so that the other packs can be turned on/off in the configuration file in case someone really wants to cherry pick them.

> P.S. the config wizard's prompts don't line up with the actual values being initialized in the config file

Ah yes, the perils of not having proper automated testing in place yet. This will be fixed as part of the configuration setup work for this issue. Thanks for the report. Getting a mock server and proper tests set up is the focus for v0.3 into v0.4, so hopefully there won't be many more silly oversights like this in the future.
