### ISSUE TITLE
[Bug]  Cannot fully download the mods 

### ISSUE THREAD

**Issue by kojah89** [RobotsOnDrugs/BDSM#30]
### Problem behavior

When i used the latest version of BDSM V 0.3.8, it was noted that the content at about 7,000 file at size 50Gb...

However it only partially downloaded, cannot fully download the update mod

For your references, here's my log

[BDSM.log](https://github.com/RobotsOnDrugs/BDSM/files/10471703/BDSM.log)

### Expected behavior

Succesfully download all of the update

**Comment by RobotsOnDrugs** [comment]
Did it give you any errors, or did it just stop? Provide a screenshot without displaying the full summaries. Also, try again with a debug build and upload the debug log.

**Comment by kojah89** [comment]
> Did it give you any errors, or did it just stop? Provide a screenshot without displaying the full summaries. Also, try again with a debug build and upload the debug log.

It was not shown any errors, it just stop without any information ...

for your references, heres my changelog when using the debug version
[BDSM.debug.log](https://github.com/RobotsOnDrugs/BDSM/files/10471784/BDSM.debug.log)
[BDSM.log](https://github.com/RobotsOnDrugs/BDSM/files/10471785/BDSM.log)

**Comment by RobotsOnDrugs** [comment]
Okay, the debug log helps immensely. This should be an easy fix, but I'll have to finish up the new feature work in progress first to keep my commits smaller. Also, I've opened #31 because it really should be showing an error whenever it gives up for any reason. In your case, it's giving up too easily though.

I'll push a release once the new feature work and the 2 bugs here are squashed.

**Comment by RobotsOnDrugs** [comment]
This is fixed in 0.3.9. Feel free to reopen if you are still experiencing the same or a similar issue.
