### ISSUE TITLE
[Feature Request] Include the most basic instructions for initiating this program

### ISSUE THREAD

**Issue by SirBalmore** [RobotsOnDrugs/BDSM#32]
I see links and promos to download this. I am definitely hesitant to do so without even the slightest bit of instructions on how to use this. It says you must be familiar with command line operations...I can use Linux so Windows command lines are more of a pain but easily doable. But including the most basic instructions would be a definite asset and increase usage. Instructions here and in your promos.

**Comment by RobotsOnDrugs** [comment]
What do you feel is missing? The first time you use it, it will walk you through creating a configuration file, and then you follow the prompts. You don't even need to start it from a terminal. I imagine most people just double-click the file.

**Comment by RobotsOnDrugs** [comment]
I can add something like "simply run the file" as the readme says when I post in the Discord server, but other than that, I'm not really sure what to change. I try to make things simpler for end users and hate to close an issue like this without any change if there's a real problem with discoverability of instructions, but there's been no response and everything seems pretty simple with no other reports like this. If you have any comments or questions, please post them. Otherwise, I will close this with nothing to change.
