### ISSUE TITLE
[Bug] Possible issue with very large files? (2GB+)

### ISSUE THREAD

**Issue by ssj4maiko** [RobotsOnDrugs/BDSM#9]
While redownloading everything (almost finishing), I noticed that one mod has been crashing, and it's exactly this one: `Sideloader Modpack - Studio/Rose/[Rose] Rose - Meadow v1.0.0.zipmod`

2x it crashed soon after restarting, and the second time I checked how much of the file it had downloaded, and it was 2GB. I'm not sure if I was just unlucky or if there could be some limitation in dealing with large files.

Now I decided to download via browser so that I can be sure I can resume downloads at least.

Using latest 0.2.1 version

**Comment by RobotsOnDrugs** [comment]
I appreciate the reports, but please use the bug report template and paste all relevant information next time. It's difficult to know what to look at without even an error message.

In this case however, since you provided an exact file, I was able to test it and track down the problem. A silly oversight with integer multiplication causing problems for files >2GB, but easily fixed.

**Comment by ssj4maiko** [comment]
> but please use the bug report template and paste all relevant information next time.

Oh yeah, you are right, my problem was that I was doing the update on my laptop (_I had to download a ton of stuff, so I just moved the SSD to a USB3 adapter, laptops save more energy after all and I could just keep it on for as long as it needed_), meanwhile I was reporting on my desktop, so I was unable to easily Ctrl+C / Ctrl+V anything.

But shouldn't be a problem from here on.
